# Generated by Django 4.1 on 2022-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'STARTED'), ('PENDING', 'PENDING'), ('HALF COMPLETED', 'HALF COMPLETED'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], max_length=50, null=True)),
                ('due_date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
