# Generated by Django 4.1 on 2022-08-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('HALF COMPLETED', 'Half Completed'), ('DONE', 'Done'), ('OVERDUE', 'Overdue')], max_length=50, null=True),
        ),
    ]
